### ISSUE TITLE
Non-slanted \leq

### ISSUE THREAD

**Issue by paulhersch** [fsrmatheinfo/mluexercise#8]
Its not that bad but i'd like to use the standard \leq from amssymb. Didn't find a call yet to either ignore the eulervm package when using \leq or to specifically use amssymb with \leq yet, hence I didn't contribute myself.

**Comment by janheinrichmerker** [comment]
The `mluexercise` class loads the [`eulervm` package](https://www.ctan.org/pkg/eulervm). This package replaces the ≥, ≤ symbols by ⩾, ⩽ for esthetical reasons. Even though both variants mean the same, if you don't like the slanted variant you can change it as described here: https://tex.stackexchange.com/a/298370/116324
However at the moment we don't see a reason to replace the symbol in `mluexercise`.
